export const SET_CURRENCY = "SET_CURRENCY";
export const SET_VALUE = "SET_VALUE";
export const SET_CONVERTABLE = "SET_CONVERTABLE";
export const SET_CONVERTED = "SET_CONVERTED";
export const SET_CONVERTED_VALUE = "SET_CONVERTED_VALUE";
export const SET_LOADING_STATE = "SET_LOADING_STATE";